#!/bin/bash

if [ $UID -eq 0 ]; then
	if [ -e installed-files.txt ]; then
		for i in $( cat installed-files.txt ); do
			if [ -e '/'$i ]; then
				rm '/'$i
			fi
		done
	fi
else
	echo "Run this file as root (ex: sudo $0)."
fi
