#!/bin/bash

if [ $UID -eq 0 ]; then
	if [ -e installed-files.txt ]; then
		for i in $( cat installed-files.txt ); do
			if [ -e '/'$i ]; then
				rm -fv '/'$i
			fi
		done
		rm -f installed-files.txt
	fi
	rm -Rfv build
	rm -fv ~/.curlew.cfg
else
	echo "Run this file as root (ex: sudo $0)."
fi
