#!/usr/bin/python

import os
import os.path
import commands

svg_files = commands.getoutput('ls *.svg').split()
for svg_file in svg_files:
	png_file  = os.path.splitext(svg_file)[0] + '.png'
	os.system('inkscape -z --export-png=%s --export-width=48 --export-height=48 %s' % (png_file,svg_file))
