.TH Curlew "1" "January 2017" "Curlew" "User Commands"
.SH NAME
curlew \- Easy to use multimedia converter
.SH DESCRIPTION
Curlew is an easy to use, Free and Open-Source Multimedia converter for Linux.
.br
Curlew written in python and GTK3 and it depends on (ffmpeg/avconv).
.SH AUTHOR
Written by Fayssal Chamekh <chamfay@gmail.com>
.SH "REPORTING BUGS"
Homepage: <http://sourceforge.net/projects/curlew>
.br
Report bugs to <https://github.com/chamfay/Curlew/issues>
.SH COPYRIGHT
(C) Copyright 2012 Fayssal Chamekh <chamfay@gmail.com>
.br
License: Waqf Public License
.br
the complete text of the Waqf Public License
.br
can be found at `http://ojuba.org/waqf/license'
.PP
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law
.br
